### PR TITLE
Fix jumps of unstyled content and test freezes, credit to @simonihmig, fixes #44

### LINKED ISSUE #44: Jumps of unstyled content and test freezes from display none
1. When an element query element initially renders, it appears unstyled.
2. When `display: none` is applied to an element query element or any of its parents, Ember tests would pause forever because of `ember-element-query` test waiter.

Both issues are caused by the fact that the initial applying of element queries is asynchronous and channeled through ResizeObserver. Running the initial applying synchronously should fix them.

Details discovered by @simonihmig.

### PR DESCRIPTION
**Pull request by lolmaus**
#44

### CODE REVIEW

File: addon/-private/modifier.ts [hunk 1]
```diff
@@ -544,20 +542,16 @@ export default class ElementQueryModifier extends Modifier<ModifierArgs> {
       : sizeObjectsSortedAsc[sizeObjectsSortedAsc.length - 1];
   }
 
-  _maybeRunPromiseResolveHasBeenInstalled(): void {
-    if (this._promiseResolveHasBeenInstalled) {
-      this._promiseResolveHasBeenInstalled();
-      this._promiseResolveHasBeenInstalled = undefined;
-    }
+  __didResizeHandler(): void {
```
Comment (simonihmig) [inline addon/-private/modifier.ts]: I had to look a couple of times to realize this hasn't the same name like the other method. Maybe call this `_didResizeHandlerSync` instead?

File: addon/-private/modifier.ts [hunk 2]
```diff
@@ -11,7 +11,6 @@ import {
   SIZES_HEIGHT_DEFAULT,
 } from 'ember-element-query';
 import { inject as service } from '@ember/service';
-import { waitFor } from '@ember/test-waiters';
```
Comment (simonihmig) [inline addon/-private/modifier.ts:14]: It seems this is unused now, so you can remove from `dependencies`.

**Review by simonihmig — APPROVED** [review]
Looks good!

CI didn't run before, it was disabled due to inactivity. I enabled it, so maybe you should force push again to trigger it!?
